Metrics small fixes
GSA/datagov-wptheme pull request #785
Opened 2017-06-16 16:04 UTC by John123Yu

2017-06-16 16:05 UTC, John123Yu commented
bootstrap-flexbox is available in bootstrap 4. Using native flexbox css

2017-06-27 16:27 UTC, vasili4 requested changes
please move all `style="..."` to css

2017-06-28 14:59 UTC, John123Yu commented
Also rearranged the css for metrics page. Rearranged the classes by alphabetical order

2017-06-30 17:09 UTC, vasili4 approved these changes

2017-06-30 17:09 UTC, merged